print("CALCULO PROMEDIO DE MATERIAS")
examen_mate=float(input("INGRESE LA NOTA DEL EXAMEN DE MATEMATICAS:  "))
nota_uno_mate=float(input("INGRESE LA PRIMERA NOTA DE MATEMATICAS:  "))
nota_dos_mate=float(input("INGRESE LA SEGUNDA NOTA DE MATEMATICAS:  "))
nota_tres_mate=float(input("INGRESE LA TERCERA NOTA DE MATEMATICAS:  "))
nota_mate=((nota_uno_mate+nota_dos_mate+nota_tres_mate)/3)
promedio_mate=((examen_mate*0.9)+(nota_mate*0.1))
print(" SU NOTA DE MATEMATICAS ES:  ", promedio_mate)
examen_fisi=float(input("INGRESE LA NOTA DEL EXAMEN DE FISICA: "))
nota_uno_fisi=float(input("INGRESE LA PRIMERA NOTA FISICA:  "))
nota_dos_fisi=float(input("INGRESE LA SEGUNDA NOTA DE FISICA:  "))
nota_tres_fisi=float(input("INGRESE LA TERCERA NOTA DE FISICA:  "))
nota_fisi=((nota_uno_fisi+nota_dos_fisi+nota_tres_fisi)/3)
promedio_fisi=((examen_fisi*0.8)+(nota_fisi*0.2))
print("SU NOTA DE FISICA ES:  ", promedio_fisi)
examen_quimi=float(input("INGRESE LA NOTA DEL EXAMEN DE QUIMICA:  "))
nota_uno_quimi=float(input("INGRESE LA PRIMERA NOTA DE QUIMICA:  "))
nota_dos_quimi=float(input("INGRESE LA SEGUNDA NOTA DE QUIMICA:  "))
nota_tres_quimi=float(input("INGRESE LA TERCERA NOTA DE QUIMICA:  "))
nota_quimi=((nota_uno_quimi+nota_dos_quimi+nota_tres_quimi)/3)
promedio_quimi=((examen_quimi+0.85)+(nota_quimi*0.15))
print("SU NOTA DE QUIMICA ES:  ", promedio_quimi)
promedio_general=((promedio_mate+promedio_fisi+promedio_quimi)/3)
print("SU PROMEDIO EN NOTA DE LAS TRES MATERIAS ES DE:  ", promedio_general)
